2023-03-01 12:54:37,371 [MainThread  ] [INFO ] [root]  STARTING BROWSER: /home/jake/chromium/src/out/direct_pointers_full_gc/chrome
2023-03-01 12:54:37,371 [MainThread  ] [INFO ] [root]  STARTING BROWSER: driver: /home/jake/chromium/src/out/direct_pointers_full_gc/chromedriver
2023-03-01 12:54:37,371 [MainThread  ] [INFO ] [root]  STARTING BROWSER: args: --no-default-browser-check --disable-component-update --disable-sync --no-experiments --enable-benchmarking --disable-extensions --no-first-run --disable-background-timer-throttling --disable-renderer-backgrounding --no-sandbox --window-size=1500,1000 --enable-logging --log-file=/home/jake/handles_numbers/no_compact_with_stack_30_iters/chrome_v112_chrome-direct-no-compact_no_sandbox_js_flags_no_compact_with_stack/speedometer_2.1/6/browser.chrome.log --js-flags=--no-compact-with-stack
2023-03-01 12:54:41,362 [MainThread  ] [INFO ] [root]  RUNNING STORY
2023-03-01 12:56:47,961 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18584b9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9649878ccea02ab3817f4b4c9fd7cdb
2023-03-01 12:56:47,962 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18584b4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9649878ccea02ab3817f4b4c9fd7cdb
2023-03-01 12:56:47,962 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18584b460>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9649878ccea02ab3817f4b4c9fd7cdb
