2023-02-22 05:02:12,518 [MainThread  ] [INFO ] [root]  STARTING BROWSER: /home/jake/research/chromium/src/out/direct-handles-no-gc/chrome
2023-02-22 05:02:12,518 [MainThread  ] [INFO ] [root]  STARTING BROWSER: driver: /home/jake/research/chromium/src/out/direct-handles-no-gc/chromedriver
2023-02-22 05:02:12,518 [MainThread  ] [INFO ] [root]  STARTING BROWSER: args: --no-default-browser-check --disable-component-update --disable-sync --no-experiments --enable-benchmarking --disable-extensions --no-first-run --disable-background-timer-throttling --disable-renderer-backgrounding --window-size=1500,1000 --enable-logging --log-file=/home/jake/research/v8_handles_experiments/crossbench/chrome_v112_chrome-direct-no-gc_default/speedometer_2.1/3/browser.chrome.log
2023-02-22 05:02:15,817 [MainThread  ] [INFO ] [root]  RUNNING STORY
2023-02-22 05:04:09,436 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcaa358400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/08cc5eb1983f585644fc7cdfa93e1a80
2023-02-22 05:04:09,437 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcaa3586d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/08cc5eb1983f585644fc7cdfa93e1a80
2023-02-22 05:04:09,437 [MainThread  ] [WARNI] [urllib3.connectionpool]  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcaa358f70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/08cc5eb1983f585644fc7cdfa93e1a80
